# Generated by Django 3.2.3 on 2021-06-10 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_auto_20210605_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 12, 28, 17, 248258)),
        ),
    ]
