# Generated by Django 3.2.3 on 2021-06-11 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_alter_customer_entrydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=250)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=13, unique=True)),
                ('OpeningTime', models.TimeField()),
                ('ClosingTime', models.TimeField()),
                ('LinkedInLink', models.CharField(max_length=100)),
                ('GitLink', models.CharField(max_length=100)),
                ('TwitterLink', models.CharField(max_length=100)),
                ('FbLink', models.CharField(max_length=100)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 8, 21, 57, 652956)),
        ),
    ]
