# Generated by Django 3.2.3 on 2021-06-11 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_alter_customer_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 10, 55, 6, 491603)),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='Day',
            field=models.CharField(max_length=10),
        ),
    ]
