# Generated by Django 3.2.3 on 2021-06-11 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_alter_customer_entrydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='webresources',
            name='Day',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 10, 59, 12, 452064)),
        ),
    ]
