# Generated by Django 3.2.3 on 2021-06-11 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_auto_20210611_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 11, 0, 16, 489964)),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='FbLink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='GitLink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='LinkedInLink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='TwitterLink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
