# Generated by Django 3.2.3 on 2021-06-11 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0031_alter_customer_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 11, 28, 35, 696332)),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='ClosingTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='Day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='Location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='OpeningTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='webresources',
            name='Phone',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
